version: 2
updates:
  # Weekly security audits
  - package-ecosystem: cargo
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 0
    groups: { security: { applies-to: security-updates, patterns: ['*'] } }

  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 0
    groups: { security: { applies-to: security-updates, patterns: ['*'] } }

  # Monthly regular updates
  - package-ecosystem: cargo
    directory: /
    schedule: { interval: monthly }
    groups:
      npm: { patterns: ['*'] }
      security: { applies-to: security-updates, patterns: ['*'] }

  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
    groups:
      github-action: { patterns: ['*'] }
      security: { applies-to: security-updates, patterns: ['*'] }
