[package]
name = "versatiles_glyphs"
version = "0.1.0"
edition = "2021"
description = "A tool for generating SDF glyphs from fonts."
license = "MIT"
repository = "https://github.com/versatiles-org/versatiles-glyphs-rs"
exclude = [
	".github",
	".gitignore",
	"codecov.yml",
	"rust-toolchain.toml",
	"rustfmt.toml",
	"scripts",
	"testdata",
]

[lib]
name = "versatiles_glyphs"
path = "src/lib/mod.rs"

[[bin]]
name = "versatiles_glyphs"
path = "src/main.rs"
required-features = ["cli"]

[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
panic = "unwind"
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false
strip = true

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.31", features = ["derive", "std"], optional = true }
indicatif = "0.17.11"
prost = "0.13.5"
rstar = "0.12.2"
ttf-parser = { version = "0.25.1", features = ["std"] }

[features]
default = []
cli = ["dep:clap"]
