name: Release Binaries

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  release-linux:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
          - target: aarch64-unknown-linux-musl
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Download cross
        run: |
          curl -L https://github.com/cross-rs/cross/releases/latest/download/cross-x86_64-unknown-linux-gnu.tar.gz \
            -o cross-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf cross-x86_64-unknown-linux-gnu.tar.gz
          sudo mv cross /usr/local/bin/cross
          sudo chmod +x /usr/local/bin/cross

      - name: Build with Cross
        run: cross build --release --bins --target ${{ matrix.target }}

      - name: Archive
        run: tar -czf ${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release versatiles_glyphs

      - name: Upload
        run: gh release upload "v$(scripts/get_version.sh)" ${{ matrix.target }}.tar.gz --clobber

  release-mac:
    name: release ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
          - target: x86_64-apple-darwin

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Add Target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --bins --target ${{ matrix.target }}

      - name: Archive
        run: tar -czf ${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release versatiles_glyphs

      - name: Upload
        run: gh release upload "v$(scripts/get_version.sh)" ${{ matrix.target }}.tar.gz --clobber

  finish-release:
    name: Finish release # The end is but the start of a new journey.
    needs:
      - release-linux
      - release-mac
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Finalize the release # The final stroke of the brush completes the masterpiece.
        run: gh release edit "v$(scripts/get_version.sh)" --draft=false --latest --prerelease=false

  pages:
    name: Pages
    needs: finish-release
    uses: ./.github/workflows/pages.yml
