name: Release Binaries

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  release-linux:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
          - target: aarch64-unknown-linux-musl
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Determine crate version
        run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps \
            | sed -n 's/.*"version":"\([^"]*\)".*/\1/p' \
            | head -n1)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Download cross
        run: |
          curl -L https://github.com/cross-rs/cross/releases/latest/download/cross-x86_64-unknown-linux-gnu.tar.gz \
            -o cross-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf cross-x86_64-unknown-linux-gnu.tar.gz
          sudo mv cross /usr/local/bin/cross
          sudo chmod +x /usr/local/bin/cross

      - name: Build with Cross
        run: cross build --release --bins --features="cli" --target ${{ matrix.target }}

      - name: Archive
        run: tar -czf ${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release versatiles_glyphs

      - name: Upload
        run: gh release upload "v${{ env.VERSION }}" ${{ matrix.target }}.tar.gz --clobber

  release-mac:
    name: release ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
          - target: x86_64-apple-darwin

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Add Target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --bins --features="cli" --target ${{ matrix.target }}

      - name: Archive
        run: tar -czf ${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release versatiles_glyphs

      - name: Upload
        run: gh release upload "v${{ env.VERSION }}" ${{ matrix.target }}.tar.gz --clobber
